// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHpoPw9Ai_aFotzAiKyHEpEhEijUc1rW0',
    appId: '1:881565548808:web:5c27dc59bcfa311a45ecbd',
    messagingSenderId: '881565548808',
    projectId: 'perfectly-plump-plums',
    authDomain: 'perfectly-plump-plums.firebaseapp.com',
    storageBucket: 'perfectly-plump-plums.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9vOcpTQC_tY1KpJxVkqN7Qa8jgKq7Hzg',
    appId: '1:881565548808:android:4090e7f4327ebea345ecbd',
    messagingSenderId: '881565548808',
    projectId: 'perfectly-plump-plums',
    storageBucket: 'perfectly-plump-plums.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKFWMmquOXIWdCsck8c-TYwUdi6ou_lFU',
    appId: '1:881565548808:ios:941f6e4aacb84b6e45ecbd',
    messagingSenderId: '881565548808',
    projectId: 'perfectly-plump-plums',
    storageBucket: 'perfectly-plump-plums.firebasestorage.app',
    iosBundleId: 'com.example.mikeyTwitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKFWMmquOXIWdCsck8c-TYwUdi6ou_lFU',
    appId: '1:881565548808:ios:941f6e4aacb84b6e45ecbd',
    messagingSenderId: '881565548808',
    projectId: 'perfectly-plump-plums',
    storageBucket: 'perfectly-plump-plums.firebasestorage.app',
    iosBundleId: 'com.example.mikeyTwitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHpoPw9Ai_aFotzAiKyHEpEhEijUc1rW0',
    appId: '1:881565548808:web:b1c5111957398c6c45ecbd',
    messagingSenderId: '881565548808',
    projectId: 'perfectly-plump-plums',
    authDomain: 'perfectly-plump-plums.firebaseapp.com',
    storageBucket: 'perfectly-plump-plums.firebasestorage.app',
  );
}
